store-after/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root :to => 'home#index'

  namespace :admin do
    resources :categories
    resources :products
  end
end

store-after/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

store-after/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

store-after/app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
  end
end

store-after/app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    def index
      @categories = Category.all
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def edit
      @category = Category.find(params[:id])
    end

    def create
      @category = Category.new(params[:category])
      if @category.save
        redirect_to [:admin, @category], notice: 'Category was successfully created.'
      else
        render action: "new"
      end
    end

    def update
      @category = Category.find(params[:id])
      if @category.update_attributes(params[:category])
        redirect_to [:admin, @category], notice: 'Category was successfully updated.'
      else
        render action: "edit"
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      redirect_to admin_categories_url
    end
  end
end

store-after/app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    def index
      @products = Product.all
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
    end

    def edit
      @product = Product.find(params[:id])
    end

    def create
      @product = Product.new(params[:product])
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render action: "new"
      end
    end

    def update
      @product = Product.find(params[:id])
      if @product.update_attributes(params[:product])
        redirect_to [:admin, @product], notice: 'Product was successfully updated.'
      else
        render action: "edit"
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_url
    end
  end
end

store-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :subdomain_view_path
  
  private
  
  def subdomain_view_path
    prepend_view_path "app/views/#{request.subdomain}_subdomain" if request.subdomain.present?
  end
end

store-after/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

store-after/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

store-after/app/helpers/application_helper.rb
module ApplicationHelper
end

store-after/app/helpers/categories_helper.rb
module CategoriesHelper
end

store-after/app/helpers/home_helper.rb
module HomeHelper
end

store-after/app/helpers/products_helper.rb
module ProductsHelper
end

store-after/app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

store-after/app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>

<table class="pretty">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', [:admin, category] %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
    <td><%= link_to 'Destroy', [:admin, category], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_admin_category_path %>

store-after/app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

store-after/app/views/admin/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

store-after/app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

store-after/app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table class="pretty">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', [:admin, product] %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
    <td><%= link_to 'Destroy', [:admin, product], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

store-after/app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

store-after/app/views/admin/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

store-after/app/views/application/_side.html.erb
<strong>Pages</strong>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Products", products_path %></li>
</ul>

store-after/app/views/home/index.html.erb
<h1>Welcome</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>


<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

store-after/app/views/mobile_subdomain/products/index.html.erb
<h1>Mobile Version</h1>

store-after/app/views/products/_side.html.erb
<strong>Pages</strong>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Products", products_path %></li>
  <li><%= link_to "Manage Products", admin_products_path %></li>
</ul>

store-after/app/views/products/index.html.erb
<h1>Products</h1>

<% for product in @products %>
  <div class="product">
    <%= link_to product.name, product %>
    <%= number_to_currency product.price %>
  </div>
<% end %>

store-after/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>Price: <%= number_to_currency @product.price %></p>
<p>Released: <%= @product.created_at.strftime("%B %d, %Y") %></p>
<p>Category: <%= @product.category.name %></p>
<p><%= link_to "Back to products", products_path %></p>